# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6"]
# ///
"""Fetch the VerseDB User API spec and patch what openapi-python-client can't parse.

The spec is generated by Scribe, which infers response schemas from example
payloads. That leaves three shapes the generator rejects or skips:

- Objects keyed by ID or month number (``{"5432": ...}``, ``{1: ..., 12: ...}``)
  come out as fixed ``properties`` with numeric names. They are maps, so they
  become ``additionalProperties``.
- An empty example array comes out as ``type: array`` with no ``items``, which
  drops the whole response. It gets ``items: {}`` (a list of anything).
- Number enums (the half-star ``personal_rating``) have no Python enum form, so
  the enum is dropped and the field stays a plain number.

Usage: uv run scripts/prepare_spec.py [SOURCE] [OUTPUT]
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

import yaml

DEFAULT_SOURCE = "https://versedb.com/api/docs.openapi"
DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "openapi.json"


def load(source: str) -> dict:
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source, timeout=60) as response:
            text = response.read().decode()
    else:
        text = Path(source).read_text()
    return yaml.safe_load(text)


def is_numeric_key(key: object) -> bool:
    return isinstance(key, int) or (isinstance(key, str) and key.isdigit())


def is_array(node: dict) -> bool:
    kind = node.get("type")
    return kind == "array" or (isinstance(kind, list) and "array" in kind)


def patch(node: object) -> None:
    if isinstance(node, list):
        for item in node:
            patch(item)
        return
    if not isinstance(node, dict):
        return

    properties = node.get("properties")
    if isinstance(properties, dict) and properties and all(map(is_numeric_key, properties)):
        node["additionalProperties"] = next(iter(properties.values()))
        del node["properties"]
        node.pop("required", None)

    if is_array(node) and "items" not in node and "prefixItems" not in node:
        node["items"] = {}

    enum = node.get("enum")
    if isinstance(enum, list) and any(isinstance(value, float) for value in enum):
        del node["enum"]
        node.pop("x-speakeasy-enums", None)

    for value in node.values():
        patch(value)


def main() -> None:
    source = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE
    output = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUTPUT
    spec = load(source)
    patch(spec)
    output.write_text(json.dumps(spec, indent=2, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    main()
